micronaut:
  application:
    name: BookAPI

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/bookapi
    driverClassName: org.postgresql.Driver
    username: docker
    password: docker

jpa:
  default:
    packages-to-scan:
      - 'com.felpsmac.bookapi'
    properties:
      hibernate:
      hbm2ddl:
        auto: update
      show_sql: true
